 id |        url         |                                             title                                              |                                                              notes                                                              | user_id | picture 
----+--------------------+------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------+---------+---------
  2 | 1                  | 333                                                                                            | 4444                                                                                                                            |         | 
  3 | 11                 | 3                                                                                              | 44                                                                                                                              |         | 
  4 | 1                  | 333                                                                                            | 4444                                                                                                                            |         | 
  5 | 1                  | 333                                                                                            | 4444                                                                                                                            |         | 
  6 | fdsfs              | fdsf                                                                                           | fdsfds                                                                                                                          |         | 
  7 | dewd               |                                                                                                |                                                                                                                                 |         | 
  8 | 1                  | 333                                                                                            | 4444                                                                                                                            |         | 
  9 | one                | title                                                                                          | notes                                                                                                                           |         | 
 10 | 1                  | 3                                                                                              | 4                                                                                                                               |         | 
 11 | 1                  | 3                                                                                              | 4                                                                                                                               |         | 
 12 | 1                  | 3                                                                                              | 34                                                                                                                              |         | 
 13 | 1                  | 3                                                                                              | 4                                                                                                                               |         | 
 14 | fdsfs              | fdsfd                                                                                          | fdsfds                                                                                                                          |         | 
 15 | fff                |                                                                                                |                                                                                                                                 |         | 
 16 | dsad               | dsada                                                                                          | dsad                                                                                                                            |         | 
 17 | fdsfs              | fdsf                                                                                           | fdsf                                                                                                                            |         | 
 18 | fdsf               | dsfds                                                                                          | fdsfs                                                                                                                           |         | 
 19 | dsad               | dsada                                                                                          | dsda                                                                                                                            |         | 
 20 | dsada              | dsad                                                                                           | dsada                                                                                                                           |         | 
 21 | dsad               | dsa                                                                                            | dsad                                                                                                                            |         | 
 22 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option |                                                                                                                                 |         | 
 23 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option |                                                                                                                                 |         | 
 24 | ff                 | ff                                                                                             | ff                                                                                                                              |       4 | 
 25 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option |                                                                                                                                 |         | 
 26 | 1                  | 3                                                                                              |                                                                                                                                 |         | 
 27 | a                  | c                                                                                              | d                                                                                                                               |         | 
 28 | http://flights.com | flights                                                                                        |                                                                                                                                 |         | 
 29 | f                  | f                                                                                              | f                                                                                                                               |         | 
 30 |                    |                                                                                                |                                                                                                                                 |         | 
 31 | http://flights.com | GUY                                                                                            |                                                                                                                                 |         | 
 32 | http://flights.com | GUY                                                                                            |                                                                                                                                 |         | 
 33 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 34 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 35 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 36 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 37 |                    |                                                                                                | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 38 |                    |                                                                                                |                                                                                                                                 |         | 
 39 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 40 |                    |                                                                                                | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 41 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 42 |                    |                                                                                                | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 43 | http://flights.com | GUY                                                                                            | IS THE BEST                                                                                                                     |         | 
 44 |                    | GUY                                                                                            | IS THE BEST                                                                                                                     |         | 
 45 | http://flights.com | Guy                                                                                            | Is cool                                                                                                                         |         | 
 46 |                    | Guy                                                                                            | Is cool                                                                                                                         |         | 
 47 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 48 |                    |                                                                                                | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 49 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 50 |                    |                                                                                                | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 51 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 52 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 53 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 54 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 55 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 56 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 57 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 58 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 59 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 60 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 61 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 62 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 63 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 64 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 65 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 66 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 67 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 68 | http://flights.com | guy                                                                                            |                                                                                                                                 |         | 
 69 | http://flights.com | title                                                                                          |                                                                                                                                 |         | 
 70 | //flights.com      | gut                                                                                            |                                                                                                                                 |         | 
 71 | http://flights.com | hh                                                                                             |                                                                                                                                 |         | 
 72 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 73 | http://flights.com | Guy                                                                                            |                                                                                                                                 |         | 
 74 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 75 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
 76 | http://flights.com |                                                                                                |                                                                                                                                 |         | 
 77 |                    | Flights: Book Cheap Plane Tickets & Airfare on Flights.com by Expedia, a Google Flights Option | Save money & time on your next flight booking with Flights.com. Best price guaranteed on thousands of flights around the world. |         | 
(76 rows)

